--- a/.github/workflows/deprecated.yaml
+++ b/.github/workflows/deprecated.yaml
@@ -78,4 +78,4 @@
           if [[ ${NODE_VERSION} != "v${{ matrix.version }}" ]]; then
             echo "Node version is not ${{ matrix.version }}. It is $NODE_VERSION"
             exit 1
-          fi
+          fi